services:
  backend:
    build:
      context: ./backend
    container_name: website_backend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [mdms_webnet]

  frontend:
    build:
      context: ./frontend
    container_name: website_frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks: [mdms_webnet]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=f71d0251-82ad-4a6b-94ee-5dace98f8c5a.cfargotunnel.com
    networks: [mdms_webnet]

networks:
  mdms_webnet:
    driver: bridge